project_name: ecsource
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ecsource
    ldflags:
      - -s -w
      - -X github.com/tatsuo48/ecsource/main.Version={{.Version}}
      - -X github.com/tatsuo48/ecsource/main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

brews:
  - tap:
      owner: tatsuo48
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/tatsuo48/ecsource
    description: ECS Task Definition tool to display resources such as CPU, memory, and memory reservations in an easy-to-read format.
    skip_upload: auto
    test: |
      system "#{bin}/ecsource", "-v"
