package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	"github.com/olekukonko/tablewriter"
)

// Generated by https://quicktype.io

type TaskDefinitionJson struct {
	TaskDefinition TaskDefinition `json:"taskDefinition"`
}

type TaskDefinition struct {
	ContainerDefinitions    []ContainerDefinition `json:"containerDefinitions"`
	CPU                     string                `json:"cpu"`
	ExecutionRoleArn        string                `json:"executionRoleArn"`
	Family                  string                `json:"family"`
	Memory                  string                `json:"memory"`
	NetworkMode             string                `json:"networkMode"`
	PlacementConstraints    []interface{}         `json:"placementConstraints"`
	RequiresCompatibilities []string              `json:"requiresCompatibilities"`
	TaskRoleArn             string                `json:"taskRoleArn"`
}

type ContainerDefinition struct {
	Image                  string                 `json:"image"`
	Name                   string                 `json:"name"`
	CPU                    int64                  `json:"cpu"`
	MemoryReservation      int64                  `json:"memoryReservation"`
	Memory                 int64                  `json:"memory"`
	Essential              bool                   `json:"essential"`
	Environment            []Environment          `json:"environment"`
	LogConfiguration       LogConfiguration       `json:"logConfiguration"`
	Secrets                []Secret               `json:"secrets"`
	Command                []string               `json:"command"`
	DockerLabels           *DockerLabels          `json:"dockerLabels,omitempty"`
	PortMappings           []PortMapping          `json:"portMappings"`
	ReadonlyRootFilesystem *bool                  `json:"readonlyRootFilesystem,omitempty"`
	StopTimeout            *int64                 `json:"stopTimeout,omitempty"`
	VolumesFrom            []interface{}          `json:"volumesFrom"`
	FirelensConfiguration  *FirelensConfiguration `json:"firelensConfiguration,omitempty"`
}

type DockerLabels struct {
	Environment string `json:"environment"`
	Service     string `json:"service"`
	App         string `json:"app"`
}

type Environment struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type FirelensConfiguration struct {
	Options FirelensConfigurationOptions `json:"options"`
	Type    string                       `json:"type"`
}

type FirelensConfigurationOptions struct {
	ConfigFileType  string `json:"config-file-type"`
	ConfigFileValue string `json:"config-file-value"`
}

type LogConfiguration struct {
	LogDriver string                   `json:"logDriver"`
	Options   *LogConfigurationOptions `json:"options,omitempty"`
}

type LogConfigurationOptions struct {
	AwslogsGroup        string `json:"awslogs-group"`
	AwslogsRegion       string `json:"awslogs-region"`
	AwslogsStreamPrefix string `json:"awslogs-stream-prefix"`
}

type PortMapping struct {
	ContainerPort int64  `json:"containerPort"`
	HostPort      int64  `json:"hostPort"`
	Protocol      string `json:"protocol"`
}

type Secret struct {
	Name      string `json:"name"`
	ValueFrom string `json:"valueFrom"`
}

func main() {
	if len(os.Args) < 2 {
		log.Fatal("ファイル名を指定してくだい")
	}
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	var taskDefinitionJson TaskDefinitionJson
	var taskDefinition TaskDefinition
	if err := json.Unmarshal(src, &taskDefinitionJson); err != nil {
		log.Fatal(err)
	}
	if taskDefinitionJson.TaskDefinition.ContainerDefinitions == nil {
		if err = json.Unmarshal(src, &taskDefinition); err != nil {
			log.Fatal(err)
		}
	} else {
		taskDefinition = taskDefinitionJson.TaskDefinition
	}
	table := tablewriter.NewWriter(os.Stdout)
	table.SetHeader([]string{"Name", "CPU", "Memory", "MemoryReservation"})
	table.Append([]string{"Task Setting", taskDefinition.CPU, taskDefinition.Memory, taskDefinition.Memory})
	var allCPU int64
	var allMemory int64
	var allMemoryReservation int64
	for _, containerDefinition := range taskDefinition.ContainerDefinitions {
		table.Append([]string{containerDefinition.Name, fmt.Sprintf("%d", containerDefinition.CPU), fmt.Sprintf("%d", containerDefinition.Memory), fmt.Sprintf("%d", containerDefinition.MemoryReservation)})
		allCPU += containerDefinition.CPU
		allMemory += containerDefinition.Memory
		allMemoryReservation += containerDefinition.MemoryReservation
	}
	table.Append([]string{"sum of all container", fmt.Sprintf("%d", allCPU), fmt.Sprintf("%d", allMemory), fmt.Sprintf("%d", allMemoryReservation)})
	taskCPU, _ := strconv.ParseInt(taskDefinition.CPU, 10, 64)
	taskMemory, _ := strconv.ParseInt(taskDefinition.Memory, 10, 64)
	table.SetFooter([]string{"leftover", fmt.Sprintf("%d", taskCPU-allCPU), fmt.Sprintf("%d", taskMemory-allMemory), fmt.Sprintf("%d", taskMemory-allMemoryReservation)})
	table.Render()
}
