name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "^1.20"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@@v4.2.0
        with:
          version: latest
          args: release --rm-dist
        env:
          # To upload homebrew formula to other repos,
          # need to set the dedicated token having enough permissions
          # https://github.com/goreleaser/goreleaser/issues/982
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
