name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  # dispatch from tagpr.yaml workflow
  workflow_dispatch:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: "go.mod"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          version: latest
          args: release --clean
        env:
          # To upload homebrew formula to other repos,
          # need to set the dedicated token having enough permissions
          # https://github.com/goreleaser/goreleaser/issues/982
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
